### ISSUE TITLE
Can you tell me what theme is used in the example image?

### ISSUE THREAD

**Issue by djkloop** [evondev/indent-rainbow-palettes#4]
Can you tell me what theme is used in the example image?

**Comment by evondev** [comment]
I am using Evondev Dracula and custom gradient with Custom CSS JS loader
extension

Vào Th 3, 18 thg 7, 2023 lúc 13:20 djkloop ***@***.***> đã
viết:

**Comment by djkloop** [comment]
@evondev thanks
