### ISSUE TITLE
Does not affect

### ISSUE THREAD

**Issue by Asadullayev-Miri** [evondev/indent-rainbow-palettes#5]
Hi, I liked your extension very much but unfortunately, I can not enable it I have tried several methods and searched for close problems 
tried to solve it by setting JSON and even asking AI search engines, but nothing helped I can even provide TeamViewer just help to solve this problem) thanks in advance I will be so appreciated it if you mail me the solution by the way other indents colorize extensions work without problems
asadullayev.mir.ismayil@gmail.com

**Comment by evondev** [comment]
I think you should install extension Indent Rainbow first. My extension
just change setting json only and have no effects to the vscode

Vào Th 2, 24 thg 7, 2023 lúc 04:56 Asadullayev-Miri <
***@***.***> đã viết:

**Comment by Asadullayev-Miri** [comment]
Thanks a lot ! The solution was pretty simple I did not know the sequence of actions I should take it helped, and you are great I like your extension and wish you all the best good luck, and thanks again for the solution and extension!!!
