### ISSUE TITLE
Asking about image in preview

### ISSUE THREAD

**Issue by AgungSukaAFK** [evondev/indent-rainbow-palettes#7]
![preview](https://github.com/evondev/indent-rainbow-palettes/assets/84656505/3233136f-b96b-498e-8544-a93b1638e7ad)
Hello, I'm using your dracula theme, and would like to know how to create a gradient border like the one in the image above. Is there a way to make it thicker, I couldn't find any kind of `tab.activeBorderWidth` or something similar.
Thank you...

**Comment by evondev** [comment]
Hi there. Thanks for using my extension. The theme I am using is my own
theme named Evondev Dracula, and I have customized it with CSS. You can
watch it here:
https://www.youtube.com/watch?v=mTlzrtCkBAg&t=256s&pp=ygUVZXZvbmRldiB2c2NvZGUgY3VzdG9t

**Comment by AgungSukaAFK** [comment]
Thank you so much, i like the design
